 spring.application.name=gestion-contact

# Configuration de la connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/contact
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuration de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update